Exception on /runchart [POST]
Traceback (most recent call last):
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/app.py", line 273, in run_python_code
    result = bar(current_meal_data)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/bar.py", line 34, in bar
    v = int(round((overall_data[i] / recomlist[i]) * 100, 0))
                                     ~~~~~~~~~^^^
IndexError: index 12 is out of bounds for axis 0 with size 12
Exception on /runchart [POST]
Traceback (most recent call last):
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/app.py", line 267, in run_python_code
    result = bar(current_meal_data)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seon/Desktop/CambodiaNAS/bar.py", line 34, in bar
    v = int(round((overall_data[i] / recomlist[i]) * 100, 0))
                                     ~~~~~~~~~^^^
IndexError: index 12 is out of bounds for axis 0 with size 12
