Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in search_food: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: [Errno 2] No such file or directory: 'data/FoodIngredient.xlsx'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: 'Food Code'
Error in get_nutrition: only list-like objects are allowed to be passed to isin(), you passed a `int`
Error in get_ingredients: 'Ingredient Code'
Error in search_food: [Errno 2] No such file or directory: 'data/FoodData.xlsx'
Error in search_food: [Errno 2] No such file or directory: 'data/FoodData.xlsx'
Error in search_food: [Errno 2] No such file or directory: 'data/FoodData.xlsx'
Exception on /m-group [GET]
Traceback (most recent call last):
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\2024-1 식영과 사업\CambodiaNAS\app.py", line 61, in m_group
    return render_template('m_group.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\kimsy\2024-1 식영과 사업\CambodiaNAS\templates\m_group.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\kimsy\2024-1 식영과 사업\CambodiaNAS\templates\base.html", line 21, in top-level template code
    <li><a href="{{ url_for('tfh_stas') }}">Generate Statistics</a></li>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kimsy\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'tfh_stas'. Did you mean 'tfh' instead?
