Exception on /m-gandu [GET]
Traceback (most recent call last):
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\app.py", line 63, in m_gandu
    return render_template('m_gandu.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\templates\m_gandu.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\templates\base.html", line 19, in top-level template code
    <li><a href="{{ url_for('tfh') }}">24Hour Recall Method</a></li>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'tfh'. Did you mean 'static' instead?
Exception on /download_excel [GET]
Traceback (most recent call last):
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\app.py", line 204, in download_excel
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\pandas\io\excel\_xlsxwriter.py", line 197, in __init__
    from xlsxwriter import Workbook
ModuleNotFoundError: No module named 'xlsxwriter'
Exception on /download_excel [GET]
Traceback (most recent call last):
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phjgi\OneDrive\바탕 화면\4학년\방학\식영과 사업\작업\CambodiaNAS\app.py", line 210, in download_excel
    return send_file(output, attachment_filename=f'{group_name}_users.xlsx', as_attachment=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'
Error in save_group: 'DataFrame' object has no attribute 'append'
